source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'SVProgressHUD', '~> 1.1'
pod 'UIImageView-Letters', '~> 1.1'

target 'CRUDsy_Example', :exclusive => true do
  pod "CRUDsy", :path => "../"
end

target 'CRUDsy_Tests', :exclusive => true do
  pod "CRUDsy", :path => "../"

  
end
