source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CRUDsy_Example', :exclusive => true do
  pod "CRUDsy", :path => "../"
end

target 'CRUDsy_Tests', :exclusive => true do
  pod "CRUDsy", :path => "../"

  
end
